### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by InternetRamen** [Poolesville-Computer-Team/ctfalcon-new#4]
This issue is meant for PHS students to get exposure to GitHub, version control, this project specifically, and open source code.
We may have additional opportunities for public contributions.

We need a CONTRIBUTING.md in the root folder that outlines how to contribute to the project. I'll make changes to the PR as necessary, but we need at least links to get started with PRs and general best practices.

**Comment by VishakhaSNathan** [comment]
Please assign to me

**Comment by InternetRamen** [comment]
Hi @VishakhaSNathan, I really wanted PHS students to get exposure to the code base with the issue, so I won't be able to assign it to you. We'll have more opportunities for public contributors soon!

**Comment by soaphia14** [comment]
what should the contrinbuting.md contain? (is it just general steps on how to contribute, should it follow a [template](https://gist.github.com/PurpleBooth/b24679402957c63ec426))

**Comment by InternetRamen** [comment]
That's a great template! Some things we may need are:
- [Opening an Issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue)
 - Writing descriptive issues (I haven't been doing that lol)
- [Opening a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)
 - Making PRs readable and descriptive (for larger changes) for ppl who don't know how code
  - What does descriptive mean?
   - Closes Issue?
   - Screenshots?
   - Any info that the title doesn't cover
   - Limitations? Potential bugs? Best way to review?
   - What does the PR actually do?
   - A lot of this info is optional and depends on the magnitude of the PR
